name: CI Build Tests

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  node_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['10', '11', '12', '13', '14']
    name: ${{ matrix.os }} - Node ${{ matrix.node }} Test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Set up Node
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install Windows Node.js Build Tools
      if: matrix.os == 'windows-latest'
      run: npm install -g windows-build-tools --vs2015
    - name: Fetch *nix dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev
    - name: Install Dependencies
      run: npm install
    - name: Generate Prebuilds
      if: matrix.node == '12' && github.repository == 'turtlecoin/node-cryptonote-util'
      run: |
        npm install -g prebuild
        prebuild --all
    - name: Publish to NPM
      if: github.event_name == 'release' && matrix.node == '12' && matrix.os == 'ubuntu-latest' && github.repository == 'turtlecoin/node-cryptonote-util'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
